# Generated by Django 2.1 on 2018-09-08 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('code', models.CharField(max_length=11)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='boardNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='profileImage',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید عدد و بین 9 تا 15 رقم باشد.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری فقط شامل حروف انگلیسی، عدد، _ و . است.', regex='^[a-zA-Z0-9_.]*$')]),
        ),
    ]
