# Generated by Django 2.1 on 2018-08-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Tag')),
            ],
        ),
        migrations.RenameModel(
            old_name='PicPerson',
            new_name='Pic',
        ),
        migrations.AlterField(
            model_name='picpost',
            name='picAdress',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
