# Generated by Django 2.1 on 2018-08-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20180819_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pic',
            new_name='PicPerson',
        ),
    ]
