# Generated by Django 2.1 on 2018-08-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20180826_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='info',
            new_name='name',
        ),
    ]
