# Generated by Django 2.1 on 2018-08-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0007_auto_20180826_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picAddress',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='userFollower',
        ),
        migrations.AddField(
            model_name='person',
            name='profileImage',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='userFollowed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='userFollowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
