# Generated by Django 2.1 on 2018-08-28 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20180827_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain numbers,charachters, _ and .', regex='^[a-zA-Z0-9_.]*$')]),
        ),
    ]
