# Generated by Django 2.1 on 2018-09-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Person')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
            ],
        ),
    ]
