# Generated by Django 2.1 on 2018-08-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0002_auto_20180818_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PicAdress', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=250)),
                ('LikeNumber', models.IntegerField(default=0)),
                ('CommentNumber', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='pic',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post'),
        ),
    ]
