# Generated by Django 2.1 on 2018-09-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_auto_20180902_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='headComment',
        ),
    ]
