# Generated by Django 2.1 on 2018-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='PicAdress',
            field=models.ImageField(upload_to=''),
        ),
    ]
